[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "seqparser"
authors = [{name = "Jackson Sands", email = "Jbsands78@gmail.com"}]
readme = "README.md"
dynamic = ["version", "description"]